### ISSUE TITLE
Idol of the Emerald Queen

### ISSUE THREAD

**Issue by Davethedruid** [thebarrensissues/Issues#1071]
Wearing Harold's rejuvenating broach (Druid idol) adds nearly 100 heals per tick to lifebloom, stacking to rather large lifebloom ticks.

Should not affect lifebloom at all, it's meant to be a bonus to rejuvenation only.

Reproduce: Cast lifebloom look at tick heals, wear Harold's rejuvenating broach and cast lifebloom again, notice immediate massive increase in heals.

**Comment by plutonium447** [comment]
[item] Harold's Rejuvenating Broach (25643) http://db.hellfire-tbc.com/?item=25643
[spell] Lifebloom (33763) http://db.hellfire-tbc.com/?spell=33763

server rev. **10914**

**Comment by Orcfootstool** [comment]
Vice versa with Idol of the Emerald Queen (item=27886). It is increasing rejuvenation's healing when it shouldn't.

**Comment by kelno** [comment]
Probably fixed with 11062

**Comment by Davethedruid** [comment]
It's definitely not fixed still giving insane lifebloom ticks when wearing harolds. 1.1k per sec on fel armour just under 900 on normal.

**Comment by Cheelout** [comment]
Fixed.

**Comment by kelno** [comment]
Emerald Queen -> confirmed bug by Blaze

**Comment by SUN-Leekie** [comment]
Fixed in 11257.
