### ISSUE TITLE
[Arena] - Charter randomly dissapearing

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1123]
**Description:**

Okay it happens randomly but players have reported that Arena Charters (all brackets) have randomly disappeared from inventory.

Another issue is when handing in say a 2v2 charter, players have been added to my team which was handed in a week ago..

**Expected behaviour:**

Charter stays in bags...

Players join their own team when charter handed in

**Steps to reproduce the problem:**

Deletion? Just carry a charter around...

1) Create team with charter
2) Get another 2 characters to create a team with charter

![image](https://user-images.githubusercontent.com/38281939/56286200-82bfbc80-615c-11e9-9ad9-71af6c2e4cf8.png)

**Comment by Cheelout** [comment]
Ok so I think all issues are stemming from the fact when you leave an arena team it leaves in the GUI but I dont think the database is updating that you have left. Example:
I have left a 3v3 team recently, logged out and in and when I try get people to sign my new charter it says "Modelol is already part of a team that size"

Also the armoury shows me as being in a 2's team (Which is pulled from the DB) but it is not showing up in the GUI, I never joined this team as well.

**Comment by kelno** [comment]
Thanks for all the details.
Fixed with 11032

**Comment by Cheelout** [comment]
![image](https://user-images.githubusercontent.com/38281939/56465151-7d53c200-643b-11e9-9b62-2a04ce0121c3.png)
still cant join or create a 2's team, even though it is not in the UI
Created a new team, didnt do anything, go to create it again and
![image](https://user-images.githubusercontent.com/38281939/56465156-8e9cce80-643b-11e9-8cf7-88029c579f1e.png)

**Comment by kelno** [comment]
Fixed with 11050

**Comment by dinkletron** [comment]
This is still happening as of tonight.

I am in an active 3s and 5s team, I have purchased a 2s charter and had it signed, but the team is not created upon turning it in.

If I try to create another team with the same name, it says it already exists as above.

**Comment by Cheelout** [comment]
@kelno also charters disappear on logout still

**Comment by kelno** [comment]
I can't reproduce the charters disappearing

**Comment by Cheelout** [comment]
No longer occuring, Logged out and in with Charter.
