### ISSUE TITLE
[Pet] Pets seem to wait for something before obeying follow command

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#696]
**Description:**
Pets like Water Elemental seem to be waiting for something instead of immediately following the owner when issued the follow command.
Here's how it looks in game:
https://streamable.com/yrtxc
https://streamable.com/r97c1

The pet seems to be waiting for some time instead of starting to follow the owner when issued the command.

**Steps to reproduce the problem:**

1. Order the pet to cast a spell on a target
2. Cancel it and order him to follow
3. Pet waits

**rev. hash/commit:** 

rev. 10564

**Comment by kelno** [comment]
Fixed with 10587

**Comment by artieau** [comment]
This issue still persists.
Applies to many summoned 'pets' or spells that should acquire a target.
For example the water elemental or Shaman's Searing totem etc. @kelno

**Comment by kelno** [comment]
Fixed with 10841
