### ISSUE TITLE
caster aggro pathing issue?

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#802]
**Description:**

Caster mobs seem to have pathing issues, if you los their cast, they just stand there and dont chase you.

**Current behaviour:**
Caster mobs seem to stop casting when you los them, but don't seem to chase you to re-enter los and attack again. They just stand there in combat in place.

**Expected behaviour:**

Mobs should chase you, re-enter los and start casting/attacking again.

**Steps to reproduce the problem:**

1. Blackrock sorcerer aggros onto me.
2. Mob starts casting on me.
3. I run and los mob.
4. Mob stands out of LOS in combat but does nothing. (Maybe it does not start the chase mechanic.)
5. even if i re-enter los, it does not start casting again.

![WoWScrnShot_032019_164945](https://user-images.githubusercontent.com/47015256/54663984-1a6ac480-4b37-11e9-8597-dcad9d47591b.jpg)
![WoWScrnShot_032019_164956](https://user-images.githubusercontent.com/47015256/54663992-1c348800-4b37-11e9-84ff-f09053c85dd0.jpg)

**Comment by kelno** [comment]
https://www.wowhead.com/npc=7026/blackrock-sorcerer

**Comment by Nolin7777** [comment]
happens to every caster

**Comment by kelno** [comment]
Fixed with 10860

**Comment by kelno** [comment]
Some casters might still be affected and must be modified to use the new system. Please create an issue if you encounter any of those.

**Comment by Nolin7777** [comment]
Every SmartAI caster I've tested got this bug still.
Tested on map 289 and 530.

**Comment by kelno** [comment]
Need some new ids to check then, will see if those should have been included in this update

**Comment by kelno** [comment]
Closed until given new problems here
