### ISSUE TITLE
Preparation missing in arenas

### ISSUE THREAD

**Issue by Orcfootstool** [thebarrensissues/Issues#862]
**Description:**

Preparation and Spirit Heal buff missing in BG's. Preparation reduces the power cost of spells and abilities by 100%. Spirit Heal reduces the cost of spells by 100%.

Players are buffed with Preparation (id=44521) at the start of a battleground until the game starts, the buff will then dissapear.
Players are buffed with Spirit Heal (id=44535) upon ressing at a spirit healer, buff lasts 6 seconds.

**Current behaviour:**

Buffs do not appear/work.

**Expected behaviour:**

Players are buffed with Preparation at the start of a battleground until the game starts, the buff will then dissapear.
Players are buffed with Spirit Heal upon ressing at a spirit healer, buff lasts 6 seconds.

**Steps to reproduce the problem:**

CHANGEME
1. Join a BG that has not begun, observe missing Preparation buff. 
2. Die, res at a spirit healer, observe missing Spirit Heal buff.
3. https://www.wowhead.com/spell=44535/spirit-heal
4. https://www.wowhead.com/spell=44521/preparation

**rev. hash/commit:** 

Sunstrider rev. 10725 (6796dce0c7c7+) 2019-03-23 17:24:35 +0000 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by kelno** [comment]
Broken in a recent rework

**Comment by kelno** [comment]
Preparation is fixed with 10744.
I can't reproduce the bug for spirit heal though, seems to be working for me.
Any more precise reproduce steps?

**Comment by artieau** [comment]
Also missing Preparation buff in ARENA - do you want new issue created? @kelno

**Comment by artieau** [comment]
Confirmed this is now working in BG properly.
But still not working for 60seconds intro of ARENA - do you want new ticket? @kelno

**Comment by kelno** [comment]
Fixed with 10905
